full_data <- read.csv("household_power_consumption.txt", header = T, sep = ';', nrows = 2075259, check.names = F, stringsAsFactors = F, comment.char = "", quote = '\"')
subdata <- subset(full_data, Date %in% c("1/2/2007", "2/2/2007"))
G_a_p <- as.numeric(subdata$Global_active_power)
d_e_t <- strptime(paste(subdata$Date, subdata$Time, sep = " "), "%d/%m/%Y %H:%M:%S")
sm1 <- as.numeric(subdata$Sub_metering_1)
sm2 <- as.numeric(subdata$Sub_metering_2)
sm3 <- as.numeric(subdata$Sub_metering_3)
png("plot3.png", width = 480, height = 480)
plot(d_e_t, sm1, xlab = " ", ylab = "Energy Submetering", type = "l")
lines(d_e_t, sm2, col = "red", type = "l")
lines(d_e_t, sm3, col = "blue", type = "l")
legend("topright", c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"),
       col = c("black", "red", "blue"), lty = 1, lwd = 2.5)
dev.off()