full_data <- read.csv("household_power_consumption.txt", header = T, sep = ';', nrows = 2075259, check.names = F, stringsAsFactors = F, comment.char = "", quote = '\"')
subdata <- subset(full_data, Date %in% c("1/2/2007", "2/2/2007"))
G_a_p <- as.numeric(subdata$Global_active_power)
d_e_t <- strptime(paste(subdata$Date, subdata$Time, sep = " "), "%d/%m/%Y %H:%M:%S")
png("plot2.png", width = 480, height = 480)
plot(d_e_t, G_a_p, col = "black", xlab = " ", ylab = "Global Active Power (kilowatts)", type = "l")
dev.off()